Layout page
ad410project/ad410project pull request #29
Opened 2018-05-13 19:07 UTC by ryanybrennan

Still need to add pictures to the carousel on the landing page.

2018-05-13 19:32 UTC, mcontado requested changes
Please remove all files that was added under .idea folder. Create a .gitignore file that will ignore these files.

2018-05-13 19:32 UTC, mcontado commented on .idea/ad410project.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition. instead create a .gitignore file that contains `.idea/*`

2018-05-13 19:32 UTC, mcontado commented on .idea/deployment.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/jsLibraryMappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/php.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 19:32 UTC, mcontado commented on .idea/webServers.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file addition

2018-05-13 20:05 UTC, mcontado commented on views/layout.php
> +    <link rel="stylesheet" href="views/styles/styles.css">
in your local, is it not showing "cannot resolve directory 'views'" ?

2018-05-13 20:26 UTC, mcontado approved these changes

2018-05-14 23:33 UTC, mviencek approved these changes
great job.  take a look at the sticky footer for bootstrap.  it works great

2018-05-15 04:49 UTC, merged