init commit for static home page
ad410project/ad410project pull request #45
Opened 2018-05-19 18:03 UTC by FrancescoWard

Hello team,
I hope this finds you well.
Please review for integration.
Thank you.

Francesco

2018-05-19 23:02 UTC, mcontado approved these changes

2018-05-19 23:06 UTC, mcontado requested changes
Hi Francesco, please pull the latest from Development branch into your local: ```git pull origin Development```  and then do ```git push``` again.

2018-05-20 02:10 UTC, mviencek requested changes
Head is missing title element.  Unclosed div at line 74.  Please fix.

2018-05-20 17:49 UTC, FrancescoWard commented
Hi Team,
Thanks for reviewing.
Resolved unclosed div on line #74 + minor modifications. Not perfect but better than before.
Is more reviewing required or can I merge ?
Thanks,
Francesco

2018-05-20 19:29 UTC, mviencek approved these changes
youre still missing the <title> element from the head.  Please add for your next commit.  also just an fyi, the map to calandar to map flow doesnt work.  clicking back and forth between the two tabs, the map doesn't reappear.

2018-05-21 03:44 UTC, mcontado commented on views/styles/styles.css
> +<<<<<<< HEAD
please fix this merge conflicts

2018-05-21 03:45 UTC, mcontado commented on views/styles/styles.css
> +>>>>>>> 4a8417e09bf83ecab30323f08a6729d6e2e5551f
please remove this and fix merge conflicts

2018-05-21 17:45 UTC, FrancescoWard commented
Hi Team,
Thanks for the additional review.
Please see latest. 
Francesco

2018-05-22 02:03 UTC, mcontado approved these changes

2018-05-22 02:04 UTC, merged