Adding Initial Authentication Code
ad410project/ad410project pull request #58
Opened 2018-05-25 15:43 UTC by mtolrom

Adding Initial Authentication Code

2018-05-25 17:58 UTC, mviencek requested changes
please add nbproject/project.properties and nbproject/project.xml to gitignore.

why did you remove the style.css file from layout.php?

why did you create your own config page and not use the existing one?

for your inserts and queries, your not protecting against injection.  please escape the posts or use parameterized queries.

please change require(config.php) to use configuration.php instead

2018-05-25 19:10 UTC, mviencek commented
i forgot to say that removing     <link rel="stylesheet" href="views/styles/styles.css"> broke several things

2018-05-25 19:10 UTC, mviencek commented
link rel="stylesheet" href="views/styles/styles.css"

2018-05-26 08:05 UTC, mtolrom commented
I added that config file only for testing. will remove that.
I removed the CSS to let UI people fix it. It's shifting menu items an in incorrect display.
Insert queries will not be used. Back-End team should replace that with store procedures.

2018-05-27 00:03 UTC, mviencek commented
no worries  about the sql.  for the rest of it though please remove config.php and remap references to configuration.php also add nbproject/project.properties and nbproject/project.xml to gitignore.

2018-05-27 00:52 UTC, mcontado commented on views/static/config.php
> +<?php
remove this file. we already have configuration.php

2018-05-27 00:53 UTC, mcontado commented on views/static/login.php
> +<?php
remove this file, Mekone is working on this.

2018-05-27 00:53 UTC, mcontado commented on views/static/logout.php
> +<?php
remove this file, Mekone is working on this.

2018-05-27 00:53 UTC, mcontado commented on views/static/profile.php
> +<?php
remove this file, Mekone is working on this.

2018-05-27 00:55 UTC, mcontado commented on views/static/registration.php
> +<?php
please checkout the latest registration page from the Development. try doing: ```git checkout origin/Development views/static/registration.php```

2018-05-27 00:55 UTC, mcontado commented on views/static/search_events.php
> +
remove this file, Mekone is working on this.

2018-05-27 00:55 UTC, mcontado commented on views/templates/header.php
> +<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
remove this file, Mekone is working on this.

2018-05-27 21:01 UTC, mtolrom commented
Changes have been pushed.

2018-05-28 00:53 UTC, mviencek commented
cool thank you.  i noticed that there are hard coded values in this query
  $query = "INSERT INTO Users(email, password, firstName, lastName, phoneNumber, notificationState, UserTypeId) VALUES ('$emailAddress', '$password', '$firstName', '$lastName', '$phoneNumber', 1, 1)";

was that intentional?
also could you also add the link back to the styles page.  they are aware that there is problems with the file.  they are going to fix them.

2018-05-28 00:54 UTC, mviencek commented on nbproject/project.xml
> +</project>
your nbproject stuff is still coming through

2018-05-28 00:55 UTC, mviencek commented on nbproject/project.properties
> +tags.asp=false
your nbproject stuff is still coming through

2018-05-29 03:23 UTC, mviencek commented
Can you close your pull request and resubmit it under a different name?  It's causing confusion with Development.  People aren't sure which one to merge with.  Thank you

2018-05-29 03:37 UTC, closed without merging