Sending Changes discussed via Slack
ad410project/ad410project pull request #65
Opened 2018-05-28 17:45 UTC by gshields5541

1. Changed CSS coding to restyle landing.php, registration.php, search_events.php, layout.php and the signing modal
2. Corrected an issue with the carousel in landing.php (I hope)
3. Added a banner logo (FunLogoBanner.png).
4. Replaced the pics that was part of the carousel slideshow with pics (1200 px by 600 px)
5. Moved the Search Events link that was in layout.php to header.php and created a nav link to the search_events.php page.
6. Changed the Fun_Logo1.png file to a more "serious" style
7. Implemented a color scheme discussed by the Front-End team via Slack using the following colors: #316117
#90B644
#FFFFFF
#E98341
#F2FEFE
#2D6077

2018-05-28 22:36 UTC, mviencek commented
gerald please pull the latest from development and resolve your conflicts.

2018-05-28 22:37 UTC, mviencek commented
youre missing the latest code

2018-05-28 23:43 UTC, mviencek commented
![cssbranch](https://user-images.githubusercontent.com/32376631/40631914-2d69a05e-6296-11e8-9c8d-492e601a4d29.png)
The styling is also off on a few of the pages

2018-05-29 01:36 UTC, gshields5541 commented
You mean origin/Development?

> On May 28, 2018, at 3:36 PM, mviencek <notifications@github.com> wrote:
> 
> gerald please pull the latest from development and resolve your conflicts.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ad410project/ad410project/pull/65#issuecomment-392612471>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ATQuEZIOLm5z35zA92-LabhBnhSOzFpaks5t3HvrgaJpZM4UQds->.
>

2018-05-29 01:38 UTC, mviencek commented
yes Development, not development.  Mekone named his development

2018-05-29 01:40 UTC, gshields5541 commented
Just double-checking:

Two files: I got modified version Yours say they are deleted. I’m accepting your changes.

Gerald

> On May 28, 2018, at 6:38 PM, mviencek <notifications@github.com> wrote:
> 
> yes Development, not development. Mekone named his development
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ad410project/ad410project/pull/65#issuecomment-392629038>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ATQuEQyEGIl0QZDP0JPc2ZBBmec6xa8Qks5t3KaFgaJpZM4UQds->.
>

2018-05-29 02:20 UTC, mcontado commented on models/event.php
> +    private $location;
why are these files being changed? we are not supposed to change the files under models directory. please do not change this file.

2018-05-29 02:21 UTC, gshields5541 commented on models/event.php
> +    private $location;
I didn't changed that file

2018-05-29 02:44 UTC, mcontado commented on models/event.php
> +    private $location;
yeah. but just curious why it was being added here

2018-05-29 02:58 UTC, mcontado requested changes
- [ ] Search Events are off, not showing search bar and maps.
- [ ] Do not include models/event.php changes.

2018-05-29 03:04 UTC, gshields5541 commented
Clint told me to pull the latest from Development, thus I’m assuming the change was made from that pull. But I didn’t change that file.

Sent from my iPad

> On May 28, 2018, at 7:44 PM, mcontado <notifications@github.com> wrote:
> 
> @mcontado commented on this pull request.
> 
> In models/event.php:
> 
> >      private $name;
>      private $description;
> -    private $address;
> +    private $location;
> yeah. but just curious why it was being added here
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-05-29 03:08 UTC, gshields5541 commented
I’ve only worked on CSS changes associated with the page. The Maps never worked.

Gerald

Sent from my iPad

> On May 28, 2018, at 7:58 PM, mcontado <notifications@github.com> wrote:
> 
> @mcontado requested changes on this pull request.
> 
>  Search Events are off, not showing search bar and maps.
>  Do not include models/event.php changes.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-05-29 03:14 UTC, gshields5541 commented
Have you checked that entire file? That’s a variable name change and it’s all over the events.php file.

Sent from my iPad

> On May 28, 2018, at 7:44 PM, mcontado <notifications@github.com> wrote:
> 
> @mcontado commented on this pull request.
> 
> In models/event.php:
> 
> >      private $name;
>      private $description;
> -    private $address;
> +    private $location;
> yeah. but just curious why it was being added here
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-05-29 03:19 UTC, mviencek commented
im the one that asked you to pull a current copy of dev.  your event.php file is different from the one in dev.  when you submit a pull request, it shows us the difference between what is in dev and what you are asking to pull

2018-05-29 03:21 UTC, mviencek commented
it looks like you merged with mekones at some point and time.  those variables are only called that on his branch.  unfortunately he named his branch development with a lower case d

2018-05-29 03:21 UTC, mviencek commented
the one you should be pulling from is Development with an uppercase D

2018-05-29 03:22 UTC, gshields5541 commented
Okay, and the last pull was from Development with a capital “D"

> On May 28, 2018, at 8:21 PM, mviencek <notifications@github.com> wrote:
> 
> the one you should be pulling from is Development with an uppercase D
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ad410project/ad410project/pull/65#issuecomment-392642110>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ATQuETR_EDZ37a4lvC27PRlkAMHGA_tKks5t3L7WgaJpZM4UQds->.
>

2018-05-29 03:25 UTC, mviencek commented
you must have pulled from development at one point in time though.  now you have a mix of both

2018-05-29 03:27 UTC, gshields5541 commented
I’ve copied the original events.php file from Development and pasted it over what I’ve have. 

> On May 28, 2018, at 8:25 PM, mviencek <notifications@github.com> wrote:
> 
> you must have pulled from development at one point in time though. now you have a mix of both
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ad410project/ad410project/pull/65#issuecomment-392642533>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ATQuETn3dlOUvT_QiYf7-XlnZxLeYwMTks5t3L-kgaJpZM4UQds->.
>

2018-05-29 03:28 UTC, mviencek commented
cool that should work for that file.  dont forget to commit and push

2018-05-29 04:17 UTC, mcontado commented
The maps works like this, with markers coming from API:

<img width="923" alt="screenshot 2018-05-28 21 14 18" src="https://user-images.githubusercontent.com/17444804/40637830-59c3b510-62bc-11e8-961c-2ba802b779df.png">

2018-05-29 23:43 UTC, mcontado commented
pull the latest one by: git pull origin Development

2018-05-30 01:50 UTC, mcontado approved these changes

2018-05-30 02:19 UTC, merged