MVC Code refactoring per talk with Luv
ad410project/ad410project pull request #79
Opened 2018-06-03 22:18 UTC by ryanybrennan

login, logout, profile, registration, search_events, search_events_curlAPI moved to dynamic folder and corresponding actions moved to dynamic_controller. moved php code from login, registration, and logout to dynamic_controller as per MVC. Profile page and search_events still needs to be refactored regarding php code.

Team lead: Maria Contado
Team member: Ryan Brennan

2018-06-03 22:29 UTC, ryanybrennan commented
Need to refactor current php code from straight SQL queries to more OOP code reflecting the backend classes still.

2018-06-03 23:45 UTC, mviencek requested changes
please pull dev and resolve a couple of conflicts

2018-06-04 01:52 UTC, ryanybrennan commented
Apologies for the merge conflicts, must have missed an update.

2018-06-04 15:57 UTC, mcontado requested changes
Please don't forget to add the terms and contact pages in their respective controllers and update their php.

2018-06-04 15:57 UTC, mcontado commented on controllers/static_controller.php
> -    public function terms(){
I think the terms should stay in the static controller.

2018-06-04 15:57 UTC, mcontado commented on controllers/static_controller.php
> -    public function contact() {
If you remove the contact here, please don't forget to add it in the dynamic controller. This new page got merged yesterday.

2018-06-04 15:57 UTC, mcontado commented on routes.php
> +$controllers = array('static' => ['landing', 'error'], 'dynamic' => ['home', 'error', 'registration', 'login',  'searchEvents', 'logout', 'profile']);
please don't forget to add the contact and terms

2018-06-05 01:03 UTC, mviencek commented
@ryanybrennan  are you going to be able to make the requested changes tonight or tomorrow morning so we can get you merged?

2018-06-05 01:49 UTC, ryanybrennan commented
I pushed some changes yesterday, forgot to add contact and terms back into the flow since I accidentally deleted them. Will update again once I get those fixed.

2018-06-05 01:50 UTC, ryanybrennan commented
Will be ready tonight.

2018-06-05 02:06 UTC, ryanybrennan commented
Made a new commit. Let me know if I need to change anything else. I pulled the most recent project before pushing, so I should have no merge conflicts.

2018-06-05 02:25 UTC, mviencek approved these changes

2018-06-05 03:09 UTC, mcontado approved these changes

2018-06-05 03:16 UTC, merged